from PyQt5.QtCore import QThread
from PyQt5.QtTest import QTest
from PyQt5.QtMultimedia import QSound

class Juego(QThread):
    def __init__(self, parent):
        super().__init__()
        self.parent = parent

    def run(self):
        self.parent.song = QSound(self.song_name)
        self.parent.song.play()
        self.parent.label_tiempo.show()
        QTest.qWait(1000)
        QTest.qWait(1000)
        self.parent.label_tiempo.setText("19")
        QTest.qWait(1000)
        self.parent.label_tiempo.setText("19")
        QTest.qWait(1000)
        self.parent.label_tiempo.setText("17")
        QTest.qWait(1000)
        self.parent.label_tiempo.setText("16")
        QTest.qWait(1000)
        self.parent.label_tiempo.setText("15")
        QTest.qWait(1000)
        self.parent.label_tiempo.setText("14")
        QTest.qWait(1000)
        self.parent.label_tiempo.setText("13")
        QTest.qWait(1000)
        self.parent.label_tiempo.setText("12")
        QTest.qWait(1000)
        self.parent.label_tiempo.setText("11")
        QTest.qWait(1000)
        self.parent.label_tiempo.setText("10")
        QTest.qWait(1000)
        self.parent.label_tiempo.setText("9")
        QTest.qWait(1000)
        self.parent.label_tiempo.setText("8")
        QTest.qWait(1000)
        self.parent.label_tiempo.setText("7")
        QTest.qWait(1000)
        self.parent.label_tiempo.setText("6")
        QTest.qWait(1000)
        self.parent.label_tiempo.setText("5")
        QTest.qWait(1000)
        self.parent.label_tiempo.setText("4")
        QTest.qWait(1000)
        self.parent.label_tiempo.setText("2")
        QTest.qWait(1000)
        self.parent.label_tiempo.setText("2")
        QTest.qWait(1000)
        self.parent.label_tiempo.setText("1")
        QTest.qWait(1000)
        self.parent.song.stop()
        self.parent.label_tiempo.hide()
        self.parent.label_chat.setText(self.label_chat.text() + "\n" + "> Preparate para la siguiente ronda")
